### ISSUE TITLE
why do you use Kafka

### ISSUE THREAD

**Issue by HoangNgo88** [akijowski/kafka-connector-demo#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Kafka in your project instead of others like RabbitMQ or ZeroMQ, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose Kafka instead of others like RabbitMQ or ZeroMQ

**Comment by akijowski** [comment]
Thanks for reading my project.  I make these projects as reference points for myself and my coworkers.  I was looking at ways of using Kafka locally to speed up our development process.  I don't have a good answer to your question.  I am most familiar with Kafka and that is what I use most often.
